CREATE DATABASE ADDITIONAL;

USE ADDITIONAL;


CREATE TABLE RELATIONS
(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50)
);

CREATE TABLE COUNTRIES
(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50),
RELATIONCOUNTRYID INT FOREIGN KEY REFERENCES RELATIONS(ID)
);

ALTER TABLE COUNTRIES 
ADD AREA DECIMAL(10,2)

INSERT INTO RELATIONS (NAME)
VALUES 
('Ally'),
('Neutral'),
('Enemy');

INSERT INTO COUNTRIES (NAME, RELATIONCOUNTRYID, AREA)
VALUES 
('USA', 1, 9833520),         -- Ally
('Switzerland', 2, 41285),   -- Neutral
('Russia', 3, 17098242),     -- Enemy
('France', 1, 551695),       -- Ally
('Germany', 1, 357022);      -- Ally

--PROCEDURE
CREATE PROCEDURE sp_UPDATEAREA @COUNTRYNAME NVARCHAR(50), @COUNTRYAREA DECIMAL(10,2)
AS 
BEGIN
UPDATE COUNTRIES
SET AREA = @COUNTRYAREA
WHERE NAME = @COUNTRYNAME;
END;
GO

EXEC sp_UPDATEAREA @COUNTRYNAME = 'Germany',@COUNTRYAREA = 445536;
SELECT * FROM COUNTRIES;

DROP PROCEDURE sp_UPDATEAREA

SELECT NAME, AREA
FROM COUNTRIES
WHERE NAME = 'Germany';

EXEC sp_UPDATEAREA @COUNTRYNAME = 'USA',@COUNTRYAREA = 9833521;


--FUNCTION
CREATE FUNCTION dbo.fn_TenPercentByCountryName (@CountryName NVARCHAR(50))
RETURNS DECIMAL(10,2)
AS
BEGIN
    DECLARE @Area DECIMAL(10,2);

    SELECT @Area = AREA
    FROM COUNTRIES
    WHERE Name = @CountryName;

    RETURN @Area * 0.10;
END;

SELECT dbo.fn_TenPercentByCountryName('Russia') AS TenPercentOfArea;

--TRIGGER


CREATE TRIGGER trg_AreaChanged
ON COUNTRIES
AFTER UPDATE,DELETE,INSERT
AS
BEGIN
SELECT 
i.Name AS CountryName,
i.AREA AS NewArea,
i.AREA * 0.10 AS TenPercentOfArea
FROM inserted i;
END;

UPDATE COUNTRIES
SET AREA = 500000
WHERE Name = 'Germany';


--------------------------------------------------------
SELECT COUNT(*) RELATIONCOUNTRYID FROM COUNTRIES 
GROUP BY RELATIONCOUNTRYID
---------------------------------------------------------
HAVING COUNT(*) <3;